"""initial_schema

Revision ID: 66d1ff3fb82b
Revises: 
Create Date: 2026-07-10 03:26:20.708951

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '66d1ff3fb82b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
