"""multi_tenant

Revision ID: 9c5f9e5e6df5
Revises: 66d1ff3fb82b
Create Date: 2026-07-10 20:21:50.735126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5f9e5e6df5'
down_revision: Union[str, Sequence[str], None] = '66d1ff3fb82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_ai_scores_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_ai_scores_user_job', ['user_id', 'job_id'], unique=True)

    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_cover_letters_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('cv_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_cv_profiles_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_email_queue_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_favorites_user_job', ['user_id', 'job_id'], unique=True)

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('smtp_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_smtp_configs_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smtp_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smtp_configs_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index('ix_favorites_user_job')
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_queue_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('cv_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_profiles_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cover_letters_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('ai_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_scores_user_job')
        batch_op.drop_index(batch_op.f('ix_ai_scores_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
